### PR TITLE
Add PHPCS, Clean up violations, Drop support for < PHP5.6

### PR DESCRIPTION
**Pull request by timrourke**
This PR cleans up docblocks and makes a couple formatting changes based on [PSR1](https://www.php-fig.org/psr/psr-1/), [PSR2](https://www.php-fig.org/psr/psr-2/), and [PEAR](https://pear.php.net/manual/en/standards.php) coding standards. (PEAR changes limited to nicer formatting of docblocks.)

*EDIT*: Updated this PR to also install PHPCS.

*EDIT*: Updated this PR to drop support for PHP versions lower than 5.6.

### CODE REVIEW

**Comment by timrourke** [comment]
PHPCS still reports some violations of PSR1 + PSR2, but because they involve changes to library code, I believe those changes should be deferred until the PR to add unit tests has landed: https://github.com/DataDog/php-datadogstatsd/pull/70

Here are the outstanding violations:

```bash

[1mFILE: /Users/tim/php-datadogstatsd/examples/expandedExample.php[0m
----------------------------------------------------------------------
[1mFOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE[0m
----------------------------------------------------------------------
 1 | [33mWARNING[0m | A file should declare new symbols (classes, functions,
   |         | constants, etc.) and cause no other side effects, or
   |         | it should execute logic with side effects, but should
   |         | not do both. The first symbol is defined on line 35
   |         | and the first side effect is on line 3.
----------------------------------------------------------------------


[1mFILE: /Users/tim/php-datadogstatsd/src/BatchedDogStatsd.php[0m
----------------------------------------------------------------------
[1mFOUND 1 ERROR AFFECTING 1 LINE[0m
----------------------------------------------------------------------
 33 | [31mERROR[0m | Method name "BatchedDogStatsd::flush_buffer" is not in
    |       | camel caps format
----------------------------------------------------------------------


[1mFILE: /Users/tim/php-datadogstatsd/src/DogStatsd.php[0m
----------------------------------------------------------------------
[1mFOUND 3 ERRORS AND 1 WARNING AFFECTING 4 LINES[0m
----------------------------------------------------------------------
  53 | [33mWARNING[0m | Property name "$__eventUrl" should not be prefixed
     |         | with an underscore to indicate visibility
 212 | [31mERROR[0m   | Method name "DogStatsd::serialize_tags" is not in
     |         | camel caps format
 271 | [31mERROR[0m   | Method name "DogStatsd::service_check" is not in
     |         | camel caps format
 301 | [31mERROR[0m   | Method name "DogStatsd::escape_sc_message" is not in
     |         | camel caps format
----------------------------------------------------------------------

Time: 231ms; Memory: 8Mb


```

**Comment by timrourke** [comment]
Now that unit tests have landed, I fixed the private method names that were not properly camelCased. I also added comments to ignore non-conforming methods that are already part of the public API. Don't want to change those right now as that will break the client for current users.

**Comment by timrourke** [comment]
@masci any thoughts on this one?

**Comment by timrourke** [comment]
@masci @hush-hush PHPCS is failing to install for PHP 5.3. Downgrading PHPCS to 2.9.1 would allow us to support PHP5.1+, at the cost of using a much older version of this library, which doesn't support:
- xml configuration files
- comments to ignore specific sniffs

The upshot is that we can install PHPCS 2.9.1, but we won't be able to fail builds that don't pass the sniffs because the following methods _should_ be camel-cased per PSR1 & PSR2, but are not, and are already public methods:
- `BatchedDogStatsd::flush_buffer`
- `DogStatsd::service_check`

How should we proceed? I do think it is important to establish some sanity around PHP syntax standards for the long haul.

Here's the output of PHPCS - you can see that it fails on the aforementioned method names:


```
$ vendor/bin/phpcs --standard=PSR1,PSR2 ./src

FILE: /Users/tim/php-datadogstatsd/src/BatchedDogStatsd.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 36 | ERROR | Method name "BatchedDogStatsd::flush_buffer" is not in
    |       | camel caps format
----------------------------------------------------------------------


FILE: /Users/tim/php-datadogstatsd/src/DogStatsd.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 278 | ERROR | Method name "DogStatsd::service_check" is not in camel
     |       | caps format
----------------------------------------------------------------------

Time: 125ms; Memory: 8Mb
```

**Comment by masci** [comment]
@timrourke what's the value of testing against 5.3 in your opinion? 
If not worth it, we could maybe drop 5.3 from the test matrix. If it's important to keep it, we might fix the problematic signatures and release a major version of the library, I'm fine with both.

**Comment by timrourke** [comment]
@masci Hey there! I spent some time thinking about this. It feels sensible to drop official support for < PHP 5.6. That should allow us to update some things.

Should I just ping you on the PR to let you know about cutting a major release version after the fact?

**Comment by timrourke** [comment]
@jian-wu those are an awesome 2 cents, i will split this up. got carried away! 🏃

**Comment by inverse** [comment]
Any update on this - really think we should drop anything below 5.6 now

**Comment by inverse** [comment]
@timrourke wanna split this? Def feel there are some awesome things going on in here. 

Should we bundle linters/static analysis into the dev composer dependencies or is it worth leveraging something like: https://github.com/jakzal/phpqa which you can plug in on CI?

**Comment by tmotyl** [comment]
any progress?

**Comment by inverse** [comment]
@tmotyl I would say it's dead

**Comment by gh123man** [comment]
Hey all, 

I'll be taking over maintaining this repo. 
Happy to get this merged - but will request a few changes. First - we have already dropped support for older PHP versions and are now supporting 5.6+ so this PR needs a rebase. 

Second - we should not rename the public methods even to comply with `PHPCS` as we risk breaking other users. I'd request that we explicitly ignore these public methods from PHPCS. 

Unsure if @timrourke is still willing to update this very old PR - if not I'll make the proposed changes myself.

**Comment by tmotyl** [comment]
@gh123man what about marking them as deprecated now, and remove them in some next major version?

**Comment by inverse** [comment]
@gh123man any reason to support 5.6 still since even PHP 7.2 is EOL

https://www.php.net/supported-versions.php

**Comment by gh123man** [comment]
@tmotyl Marking them as deprecated sounds good for now. 

@inverse I think it's best we leave the PHP version for now to best align with other Datadog repos. 
Do please let me know if the PHP version is a blocking issue - I'd love to gather more insights.

**Comment by inverse** [comment]
@gh123man it's not a blocking issue - just wanted to raise the fact that anything below PHP 7.3 is EOL.

**Comment by gh123man** [comment]
Hi all - I've revived this branch [here](https://github.com/DataDog/php-datadogstatsd/pull/104) with some changes to bring it up to date.

**Pull request closed without merging**
