### PR TITLE
Send events over UDP

### PR DESCRIPTION
**Pull request by onema**
- Update event method to build a datadog event string to be sent over UDP. 
- This addresses #37

### CODE REVIEW

**Comment by hkaj** [comment]
Thanks a lot @onema! That is an important feature that was missing from this library. We'll review this shortly.

**Comment by wvdeutekom** [comment]
Any progress @hkaj?

**Comment by ist-pasha** [comment]
This merge would be Pretty Darn Great™ because it also addresses the problem that the current `master` branch code isn't properly adding the `aggregation_key` to the event object in the `eventUdp()` function… Would love to see this merged in.

**Comment by hush-hush** [comment]
Hi @onema,

Thanks a lot for this PR and sorry it took us so long to come back to it. Since #41 was merged, sending events over UDP was possible.

Yet I updated the code with #48 to support every event fields (based on your PR). This should fix the `aggregation_key` issue @ist-pasha.

**Pull request closed without merging**
