### PR TITLE
Minor changes to match supported PHP versions

### PR DESCRIPTION
**Pull request by inverse**
@hush-hush related to your change :+1: 

Perhaps we should even consider dropping 5.6 as it's way past EOL.

### CODE REVIEW

**Comment by inverse** [comment]
Looks like travis is based on php 5.3 :/

**Comment by hush-hush** [comment]
Hi @inverse,

Thanks for the PR, I'm planning on updating the PHP versions we support with @SammyK in the next few weeks.

**Comment by inverse** [comment]
@hush-hush fixed :+1:

**Comment by hush-hush** [comment]
Thanks a lot @inverse !

**Pull request merged**
